language: node_js
node_js:
    - '12'
cache:
    yarn: true
    directories:
        - "node_modules"

before_install:
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
    - yarn --version
    - yarn run greenkeeper-lockfile-update

script:
    - yarn ci:build

after_script:
    - yarn run greenkeeper-lockfile-upload

before_deploy:
    - git config --global user.email ${GITHUB_EMAIL}
    - git config --global user.name ${GITHUB_USER}
    - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/sirian/js.git"
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

deploy:
    provider: script
    script: "yarn lerna:publish"
    skip_cleanup: true
    on:
        node: "12"
        branch: "master"
