language: node_js
node_js:
    - '13'
cache:
    yarn: true
    directories:
        - "node_modules"

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH=`yarn global bin`:$PATH

install:
    - yarn install --pure-lockfile
    - yarn audit

before_script:
    - yarn --version

script:
    - yarn ci:build
    - lerna updated

before_deploy:
    - git config --global user.email ${GITHUB_EMAIL}
    - git config --global user.name ${GITHUB_USER}
    - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/sirian/js.git"
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - git checkout release

deploy:
    provider: script
    script: "yarn lerna:publish"
    skip_cleanup: true
    on:
        node: "13"
        branch: "release"
