language: node_js
node_js:
    - '15'
cache:
    yarn: true

before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s
    - export PATH=`yarn global bin`:$PATH

install:
    - yarn install --pure-lockfile
    - yarn audit

before_script:
    - yarn --version

script:
    - yarn ci:build

before_deploy:
    - git config --global user.email ${GITHUB_EMAIL}
    - git config --global user.name ${GITHUB_USER}
    - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/sirian/js.git"
    - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - git checkout release

#deploy:
#    provider: script
#    script: "yarn lerna:publish"
#    skip_cleanup: true
#    on:
#        node: "15"
#        branch: "master"
